# -*- coding: utf-8 -*-
"""dados_imoveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19CSp-8LPuHAaYZMd0Fhs53xqY5yV7824
"""

import pandas as pd
url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"
dados = pd.read_csv(url)
dados.head()

dados

dados.sample(10)

type(dados)

dados["Bairro"][6522]

dados.info()

dados['Metragem'].mean()

sum((dados['Bairro'] == 'Vila Mariana')*1)

tem_imoveis_vila = dados['Bairro'] == 'Vila Mariana'
tem_imoveis_vila

imoveis_vila_mariana = dados[tem_imoveis_vila]
imoveis_vila_mariana

imoveis_vila_mariana['Metragem'].mean()

dados['Bairro'].value_counts()

n_imoveis_bairro = dados['Bairro'].value_counts()
n_imoveis_bairro.plot.hist()

n_imoveis_bairro.plot.bar()

n_imoveis_bairro.head(15).plot.bar()

